# Final Project - Establish Independent variable for Analysis

In [1]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd 
import xlrd as xl 
from pandas import ExcelWriter
from pandas import ExcelFile

In [3]:
from sklearn.cluster import KMeans  #algorithm in sklearn library to do k-means clustering

import matplotlib.pyplot as plt

%matplotlib inline

In [4]:
Location = "datasets/Sorted_final_project.xlsx"

df = pd.read_excel(Location,sheet_name='Mobility with Gender')

In [5]:

df.head()

,Unnamed: 0,ragender,ID,if Respondent W12,HOUSEHOLD IDENTIFIER,Self-report of health,Hlth problems limit work,Diff-Walk across room,Gets Help-Walk across room,Eqp-Walk across room,...,Diff-Climb one flt stair,bend,Some diff walking,Some diff walking one block,Difficulty several floors,Some Diff-Clmb 1 flt stair,Some Diff-Walk across room,Incm: Total Hhold,IS RECEIVING SSDI,Ret Satisfying
0,0,2.female,3020,"1.resp,alive",3,4.fair,1.yes,0.no,.s,1.yes,...,1.yes,1.yes,1.yes,1.yes,1.yes,1.yes,0.no,703500.0,0.no,2.moderately
1,1,1.male,10001010,"1.resp,alive",10001,3.good,0.no,0.no,.s,.s,...,0.no,0.no,0.no,0.no,0.no,0.no,0.no,12000.0,0.no,2.moderately
2,2,2.female,10003030,"1.resp,alive",10003,1.excellent,0.no,0.no,.s,.s,...,0.no,0.no,0.no,0.no,0.no,0.no,0.no,12280.0,0.no,2.moderately
3,3,2.female,10004040,"1.resp,alive",10004,1.excellent,0.no,0.no,.s,.s,...,0.no,0.no,0.no,0.no,0.no,0.no,0.no,19200.0,0.no,1.very
4,4,1.male,10013010,"1.resp,alive",10013,5.poor,0.no,0.no,.s,0.no,...,1.yes,0.no,0.no,0.no,1.yes,1.yes,0.no,15276.0,1.yes,2.moderately

In [6]:
df.dtypes

Unnamed: 0                       int64
ragender                        object
ID                               int64
if Respondent W12               object
HOUSEHOLD IDENTIFIER             int64
Self-report of health           object
Hlth problems limit work        object
Diff-Walk across room           object
Gets Help-Walk across room      object
Eqp-Walk across room            object
Diff-Managing money             object
Diff-Walk sev blocks            object
Diff-Jog one mile               object
Diff-Walk one block             object
Diff-Sit for 2 hours            object
Diff-Get up fr chair            object
Diff-Climb sev flt stair        object
Diff-Climb one flt stair        object
bend                            object
Some diff walking               object
Some diff walking one block     object
Difficulty several floors       object
Some Diff-Clmb 1 flt stair      object
Some Diff-Walk across room      object
Incm: Total Hhold              float64
IS RECEIVING SSDI               object
Ret Satisfying                  object
dtype: object

In [7]:
col_name=df.columns

In [8]:
knn_name = ['Diff-Walk across room', 
     'Diff-Walk sev blocks', 'Diff-Jog one mile',
       'Diff-Walk one block', 'Diff-Sit for 2 hours', 'Diff-Get up fr chair',
       'Diff-Climb sev flt stair', 'Diff-Climb one flt stair', 'bend',
       'Some diff walking', 'Some diff walking one block',
       'Difficulty several floors', 'Some Diff-Clmb 1 flt stair',
       'Some Diff-Walk across room']

In [9]:
#make a dataframe called X to hold the predictive features
mob_col = pd.DataFrame(df,columns=knn_name)
mob_col.head()

,Diff-Walk across room,Diff-Walk sev blocks,Diff-Jog one mile,Diff-Walk one block,Diff-Sit for 2 hours,Diff-Get up fr chair,Diff-Climb sev flt stair,Diff-Climb one flt stair,bend,Some diff walking,Some diff walking one block,Difficulty several floors,Some Diff-Clmb 1 flt stair,Some Diff-Walk across room
0,0.no,1.yes,.s,1.yes,0.no,1.yes,1.yes,1.yes,1.yes,1.yes,1.yes,1.yes,1.yes,0.no
1,0.no,0.no,1.yes,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no
2,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no
3,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no
4,0.no,0.no,1.yes,0.no,0.no,0.no,1.yes,1.yes,0.no,0.no,0.no,1.yes,1.yes,0.no

In [10]:
mob_col.dtypes

Diff-Walk across room          object
Diff-Walk sev blocks           object
Diff-Jog one mile              object
Diff-Walk one block            object
Diff-Sit for 2 hours           object
Diff-Get up fr chair           object
Diff-Climb sev flt stair       object
Diff-Climb one flt stair       object
bend                           object
Some diff walking              object
Some diff walking one block    object
Difficulty several floors      object
Some Diff-Clmb 1 flt stair     object
Some Diff-Walk across room     object
dtype: object

In [11]:
miss_dict = {"0.no":0, "1.yes": 1, ".d":np.NAN, ".r":np.NAN, ".s":np.NAN, ".x":np.NAN, "2.can't do": np.NAN, "9.don't do": np.NAN}

In [12]:
mob_col2 = mob_col.replace(miss_dict)

In [13]:
mob_col2.dtypes

Diff-Walk across room          float64
Diff-Walk sev blocks           float64
Diff-Jog one mile              float64
Diff-Walk one block            float64
Diff-Sit for 2 hours           float64
Diff-Get up fr chair           float64
Diff-Climb sev flt stair       float64
Diff-Climb one flt stair       float64
bend                           float64
Some diff walking              float64
Some diff walking one block    float64
Difficulty several floors      float64
Some Diff-Clmb 1 flt stair     float64
Some Diff-Walk across room     float64
dtype: object

In [14]:
mob_col2.describe()

,Diff-Walk across room,Diff-Walk sev blocks,Diff-Jog one mile,Diff-Walk one block,Diff-Sit for 2 hours,Diff-Get up fr chair,Diff-Climb sev flt stair,Diff-Climb one flt stair,bend,Some diff walking,Some diff walking one block,Difficulty several floors,Some Diff-Clmb 1 flt stair,Some Diff-Walk across room
count,18645.000000,18450.000000,10004.000000,18520.000000,18578.000000,18628.000000,17390.000000,18102.000000,18146.000000,18590.000000,18639.000000,18031.000000,18442.000000,18714.000000
mean,0.083239,0.330407,0.531787,0.168305,0.208795,0.399882,0.472053,0.193073,0.466274,0.335449,0.173614,0.490821,0.207949,0.086620
std,0.276251,0.470372,0.499013,0.374147,0.406459,0.489887,0.499233,0.394720,0.498875,0.472160,0.378788,0.499930,0.405851,0.281284
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [15]:
X = mob_col2.dropna()

In [16]:
X.describe()

,Diff-Walk across room,Diff-Walk sev blocks,Diff-Jog one mile,Diff-Walk one block,Diff-Sit for 2 hours,Diff-Get up fr chair,Diff-Climb sev flt stair,Diff-Climb one flt stair,bend,Some diff walking,Some diff walking one block,Difficulty several floors,Some Diff-Clmb 1 flt stair,Some Diff-Walk across room
count,9705.000000,9705.0,9705.000000,9705.0,9705.000000,9705.000000,9705.000000,9705.000000,9705.000000,9705.0,9705.0,9705.000000,9705.000000,9705.000000
mean,0.002988,0.0,0.527048,0.0,0.113447,0.224730,0.286553,0.044822,0.294487,0.0,0.0,0.286553,0.044822,0.002988
std,0.054585,0.0,0.499294,0.0,0.317154,0.417426,0.452174,0.206924,0.455835,0.0,0.0,0.452174,0.206924,0.054585
min,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
25%,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
50%,0.000000,0.0,1.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
75%,0.000000,0.0,1.000000,0.0,0.000000,0.000000,1.000000,0.000000,1.000000,0.0,0.0,1.000000,0.000000,0.000000
max,1.000000,0.0,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,1.000000,1.000000,1.000000

In [17]:
#initialize k-means function
#set number of clusters to categorize = 4
kmeans = KMeans(n_clusters=4)

#the model will learn which data points seem similar
#calculates centroids
#classfies data points in clusters based on distance to centroids
kmeans.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=4, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [18]:
#data point coordinates for centroids of each cluster
#index 0 is blue cluster
#index 1 is yellow cluster
#index 2 is purple cluster
#index 3 is red cluster
print(kmeans.cluster_centers_)

[[ 7.24987917e-04  0.00000000e+00 -1.87627691e-14  0.00000000e+00
   3.89076849e-02  7.58820686e-02 -2.94209102e-15  3.81639165e-16
   8.62735621e-02  0.00000000e+00  0.00000000e+00 -2.94209102e-15
   3.81639165e-16  7.24987917e-04]
 [ 1.06171201e-02  0.00000000e+00  8.90510949e-01  0.00000000e+00
   3.03915063e-01  6.12475116e-01  1.00000000e+00  2.18978102e-01
   9.95355010e-01  0.00000000e+00  0.00000000e+00  1.00000000e+00
   2.18978102e-01  1.06171201e-02]
 [ 2.87150036e-03  0.00000000e+00  1.00000000e+00  0.00000000e+00
   1.18449390e-01  2.19669777e-01  1.18238752e-14  3.81639165e-16
   3.59296482e-01  0.00000000e+00  0.00000000e+00  1.18238752e-14
   3.81639165e-16  2.87150036e-03]
 [ 1.56985871e-03  0.00000000e+00  7.74725275e-01  0.00000000e+00
   1.19309262e-01  2.60596546e-01  1.00000000e+00  8.24175824e-02
  -1.94289029e-15  0.00000000e+00  0.00000000e+00  1.00000000e+00
   8.24175824e-02  1.56985871e-03]]

In [19]:
#add a new column to dataframe called "cluster"
#can use this to compare features of clusters to original categories
X['cluster'] = kmeans.labels_

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [20]:
X.describe()

,Diff-Walk across room,Diff-Walk sev blocks,Diff-Jog one mile,Diff-Walk one block,Diff-Sit for 2 hours,Diff-Get up fr chair,Diff-Climb sev flt stair,Diff-Climb one flt stair,bend,Some diff walking,Some diff walking one block,Difficulty several floors,Some Diff-Clmb 1 flt stair,Some Diff-Walk across room,cluster
count,9705.000000,9705.0,9705.000000,9705.0,9705.000000,9705.000000,9705.000000,9705.000000,9705.000000,9705.0,9705.0,9705.000000,9705.000000,9705.000000,9705.000000
mean,0.002988,0.0,0.527048,0.0,0.113447,0.224730,0.286553,0.044822,0.294487,0.0,0.0,0.286553,0.044822,0.002988,1.123235
std,0.054585,0.0,0.499294,0.0,0.317154,0.417426,0.452174,0.206924,0.455835,0.0,0.0,0.452174,0.206924,0.054585,1.106108
min,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.0,1.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,1.000000
75%,0.000000,0.0,1.000000,0.0,0.000000,0.000000,1.000000,0.000000,1.000000,0.0,0.0,1.000000,0.000000,0.000000,2.000000
max,1.000000,0.0,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,1.000000,1.000000,1.000000,3.000000

In [21]:
X['cluster'].unique()

array([2, 0, 3, 1], dtype=int64)