# Final Project - Establish Independent variable for Analysis

In [1]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd 
import xlrd as xl 
from pandas import ExcelWriter
from pandas import ExcelFile

In [3]:
from sklearn.cluster import KMeans  #algorithm in sklearn library to do k-means clustering

import matplotlib.pyplot as plt

%matplotlib inline

In [4]:
Location = "datasets/Sorted_final_project.xlsx"

df = pd.read_excel(Location,sheet_name='Mobility with Gender')

In [5]:

df.head()

,Unnamed: 0,ragender,ID,if Respondent W12,HOUSEHOLD IDENTIFIER,Self-report of health,Hlth problems limit work,Diff-Walk across room,Gets Help-Walk across room,Eqp-Walk across room,...,Diff-Climb one flt stair,bend,Some diff walking,Some diff walking one block,Difficulty several floors,Some Diff-Clmb 1 flt stair,Some Diff-Walk across room,Incm: Total Hhold,IS RECEIVING SSDI,Ret Satisfying
0,0,2.female,3020,"1.resp,alive",3,4.fair,1.yes,0.no,.s,1.yes,...,1.yes,1.yes,1.yes,1.yes,1.yes,1.yes,0.no,703500.0,0.no,2.moderately
1,1,1.male,10001010,"1.resp,alive",10001,3.good,0.no,0.no,.s,.s,...,0.no,0.no,0.no,0.no,0.no,0.no,0.no,12000.0,0.no,2.moderately
2,2,2.female,10003030,"1.resp,alive",10003,1.excellent,0.no,0.no,.s,.s,...,0.no,0.no,0.no,0.no,0.no,0.no,0.no,12280.0,0.no,2.moderately
3,3,2.female,10004040,"1.resp,alive",10004,1.excellent,0.no,0.no,.s,.s,...,0.no,0.no,0.no,0.no,0.no,0.no,0.no,19200.0,0.no,1.very
4,4,1.male,10013010,"1.resp,alive",10013,5.poor,0.no,0.no,.s,0.no,...,1.yes,0.no,0.no,0.no,1.yes,1.yes,0.no,15276.0,1.yes,2.moderately

In [6]:
df.dtypes

Unnamed: 0                       int64
ragender                        object
ID                               int64
if Respondent W12               object
HOUSEHOLD IDENTIFIER             int64
Self-report of health           object
Hlth problems limit work        object
Diff-Walk across room           object
Gets Help-Walk across room      object
Eqp-Walk across room            object
Diff-Managing money             object
Diff-Walk sev blocks            object
Diff-Jog one mile               object
Diff-Walk one block             object
Diff-Sit for 2 hours            object
Diff-Get up fr chair            object
Diff-Climb sev flt stair        object
Diff-Climb one flt stair        object
bend                            object
Some diff walking               object
Some diff walking one block     object
Difficulty several floors       object
Some Diff-Clmb 1 flt stair      object
Some Diff-Walk across room      object
Incm: Total Hhold              float64
IS RECEIVING SSDI               object
Ret Satisfying                  object
dtype: object

In [7]:
col_name=df.columns

In [23]:
knn_name = ['Diff-Walk across room', 
     'Diff-Walk sev blocks',
       'Diff-Walk one block', 'Diff-Sit for 2 hours', 'Diff-Get up fr chair',
       'Diff-Climb sev flt stair', 'Diff-Climb one flt stair', 'bend',
       'Some diff walking', 'Some diff walking one block',
       'Difficulty several floors', 'Some Diff-Clmb 1 flt stair',
       'Some Diff-Walk across room']

In [24]:
#make a dataframe called X to hold the predictive features
mob_col = pd.DataFrame(df,columns=knn_name)
mob_col.head()

,Diff-Walk across room,Diff-Walk sev blocks,Diff-Walk one block,Diff-Sit for 2 hours,Diff-Get up fr chair,Diff-Climb sev flt stair,Diff-Climb one flt stair,bend,Some diff walking,Some diff walking one block,Difficulty several floors,Some Diff-Clmb 1 flt stair,Some Diff-Walk across room
0,0.no,1.yes,1.yes,0.no,1.yes,1.yes,1.yes,1.yes,1.yes,1.yes,1.yes,1.yes,0.no
1,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no
2,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no
3,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no
4,0.no,0.no,0.no,0.no,0.no,1.yes,1.yes,0.no,0.no,0.no,1.yes,1.yes,0.no

In [25]:
mob_col.dtypes

Diff-Walk across room          object
Diff-Walk sev blocks           object
Diff-Walk one block            object
Diff-Sit for 2 hours           object
Diff-Get up fr chair           object
Diff-Climb sev flt stair       object
Diff-Climb one flt stair       object
bend                           object
Some diff walking              object
Some diff walking one block    object
Difficulty several floors      object
Some Diff-Clmb 1 flt stair     object
Some Diff-Walk across room     object
dtype: object

In [26]:
miss_dict = {"0.no":0, "1.yes": 1, ".d":np.NAN, ".r":np.NAN, ".s":np.NAN, ".x":np.NAN, "2.can't do":0, "9.don't do":1}

In [27]:
mob_col2 = mob_col.replace(miss_dict)

In [28]:
mob_col2.dtypes

Diff-Walk across room          float64
Diff-Walk sev blocks           float64
Diff-Walk one block            float64
Diff-Sit for 2 hours           float64
Diff-Get up fr chair           float64
Diff-Climb sev flt stair       float64
Diff-Climb one flt stair       float64
bend                           float64
Some diff walking              float64
Some diff walking one block    float64
Difficulty several floors      float64
Some Diff-Clmb 1 flt stair     float64
Some Diff-Walk across room     float64
dtype: object

In [29]:
mob_col2.describe()

,Diff-Walk across room,Diff-Walk sev blocks,Diff-Walk one block,Diff-Sit for 2 hours,Diff-Get up fr chair,Diff-Climb sev flt stair,Diff-Climb one flt stair,bend,Some diff walking,Some diff walking one block,Difficulty several floors,Some Diff-Clmb 1 flt stair,Some Diff-Walk across room
count,18715.000000,18710.000000,18714.000000,18717.000000,18700.000000,18685.000000,18701.000000,18691.000000,18590.000000,18639.000000,18031.000000,18442.000000,18714.000000
mean,0.083730,0.332229,0.170567,0.211359,0.399358,0.474338,0.200738,0.460061,0.335449,0.173614,0.490821,0.207949,0.086620
std,0.276989,0.471025,0.376141,0.408283,0.489780,0.499354,0.400563,0.498416,0.472160,0.378788,0.499930,0.405851,0.281284
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [30]:
X = mob_col2.dropna()

In [31]:
X.describe()

,Diff-Walk across room,Diff-Walk sev blocks,Diff-Walk one block,Diff-Sit for 2 hours,Diff-Get up fr chair,Diff-Climb sev flt stair,Diff-Climb one flt stair,bend,Some diff walking,Some diff walking one block,Difficulty several floors,Some Diff-Clmb 1 flt stair,Some Diff-Walk across room
count,17739.000000,17739.000000,17739.000000,17739.000000,17739.000000,17739.000000,17739.000000,17739.000000,17739.000000,17739.000000,17739.000000,17739.000000,17739.000000
mean,0.080444,0.319522,0.163369,0.210440,0.394216,0.452168,0.188849,0.455494,0.326287,0.169288,0.485315,0.205479,0.083094
std,0.271987,0.466305,0.369712,0.407633,0.488695,0.497721,0.391400,0.498029,0.468867,0.375017,0.499798,0.404063,0.276032
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [32]:
#initialize k-means function
#set number of clusters to categorize = 4
kmeans = KMeans(n_clusters=3)

#the model will learn which data points seem similar
#calculates centroids
#classfies data points in clusters based on distance to centroids
kmeans.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [33]:
np.set_printoptions(suppress=True,precision=1)

In [34]:
#data point coordinates for centroids of each cluster
#index 0 is blue cluster
#index 1 is yellow cluster
#index 2 is purple cluster
#index 3 is red cluster
print(kmeans.cluster_centers_)

[[0.  0.  0.  0.1 0.1 0.  0.  0.2 0.  0.  0.  0.  0. ]
 [0.4 1.  0.7 0.5 0.8 0.9 0.7 0.8 1.  0.8 1.  0.8 0.4]
 [0.  0.3 0.  0.3 0.5 1.  0.1 0.6 0.3 0.  1.  0.1 0. ]]

In [35]:
#add a new column to dataframe called "cluster"
#can use this to compare features of clusters to original categories
X['cluster'] = kmeans.labels_

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [39]:
import seaborn as sns

In [36]:
X.describe()

,Diff-Walk across room,Diff-Walk sev blocks,Diff-Walk one block,Diff-Sit for 2 hours,Diff-Get up fr chair,Diff-Climb sev flt stair,Diff-Climb one flt stair,bend,Some diff walking,Some diff walking one block,Difficulty several floors,Some Diff-Clmb 1 flt stair,Some Diff-Walk across room,cluster
count,17739.000000,17739.000000,17739.000000,17739.000000,17739.000000,17739.000000,17739.000000,17739.000000,17739.000000,17739.000000,17739.000000,17739.000000,17739.000000,17739.000000
mean,0.080444,0.319522,0.163369,0.210440,0.394216,0.452168,0.188849,0.455494,0.326287,0.169288,0.485315,0.205479,0.083094,0.767462
std,0.271987,0.466305,0.369712,0.407633,0.488695,0.497721,0.391400,0.498029,0.468867,0.375017,0.499798,0.404063,0.276032,0.854435
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,2.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000

In [22]:
X['cluster'].unique()

array([0, 2, 1], dtype=int64)

In [38]:
X['cluster'].value_counts()

0    9017
2    4892
1    3830
Name: cluster, dtype: int64

In [ ]:
#scatterplot of k-means predicted clusters with calculated centroids
sns.scatterplot(x=X[''],y=X[''], hue=X['cluster'])
#k-means predicted clusters for the original data features
plt.scatter(x=X['feature1'],y=X['feature2'], c=df['cluster'], cmap= 'rainbow')

#plot x, y axis coordinates for centroids
plt.scatter(kmeans.cluster_centers_[:,0], kmeans.cluster_centers_[:,1], c='black')